name: Lint and Build
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # Pin pnpm version
          version: 8
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          # Pin node version
          node-version: 18.x
          # Use pnpm as cache
          cache: "pnpm"
      - name: Install packages
        #  Don't generate a lockfile and fail if an update is needed.
        run: pnpm install --frozen-lockfile
      - name: Lint and Build
        # Check linting and bundle package
        run: pnpm run lint && pnpm run build
